name: Docker conatiner
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vinodn13/python_flask:"${{GITHUB_SHA}}"
          
      - name: EXECUTE DOCKER COMMAND 
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker service update --replica=2 vinodn13/python_flask:"${{GITHUB_SHA}}"
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.DOCKER_SSH_PRIVATE_KEY}}
